[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
authors = ["Arys"]


[[bench]]
name = "day1"
harness = false

[lib]
bench = false

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
criterion = "0.5.1"
