[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
authors = ["Arys"]


[[bench]]
name = "day1"
harness = false

[[bench]]
name = "day2"
harness = false

[lib]
bench = false

[dependencies]
criterion = "0.5.1"
